channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=23.3.2
- pip:
  - mlflow<3,>=2.3
  - cloudpickle==2.2.1
  - numpy==1.26.2
  - psutil==5.9.5
  - scikit-learn==1.2.2
  - scipy==1.11.4
name: mlflow-env
